# Generated by Django 4.0.5 on 2022-06-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='sub_cat_image',
            field=models.ImageField(blank=True, upload_to='photos/sub_categories'),
        ),
    ]
