# Generated by Django 4.0.5 on 2022-07-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
